apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  env: {{ .Values.env }}
  project: {{ .Values.projName }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        env: {{ .Values.env }}
        project: {{ .Values.projName }}
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
