---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgstac
  labels:
    env: {{ .Values.env }}
    project: {{ .Values.projName | default "unknownProjName" }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        env: {{ .Values.env }}
        project: {{ .Values.projName | default "unknownProjName" }}
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
