---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cdstheia-preprod
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    applicationsSync: create-update
  generators:
    - git:
        repoURL: https://github.com/cedef/argocd-example-apps.git
        revision: HEAD
        directories:
          - path: helm-charts/*
  template:
    metadata:
      name: '{{.path.basename}}-preprod'
      namespace: argocd
      labels:
        app: '{{.path.basename}}'
        env: preprod
    spec:
      project: default
      source:
        repoURL: https://github.com/cedef/argocd-example-apps.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        helm:
          valueFiles:
          - ../global-values.yaml
          - ../global-values-preprod.yaml
          - values.yaml
          - values-preprod.yaml
          ignoreMissingValueFiles: true
      destination:
        server: https://kubernetes.default.svc
        namespace: test-preprod
  templatePatch: |
    spec:
    {{- if eq $.path.basename "stacapi" }}
      syncPolicy:
        automated:
          prune: true
    {{- else }}
      syncPolicy: {}
    {{- end }}
