---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdstheia-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
spec:
  project: default
  source:
    repoURL: https://github.com/cedef/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-charts
    helm:
      valueFiles:
      - values.yaml
      - values-prod.yaml
      ignoreMissingValueFiles: false
  destination:
    server: https://kubernetes.default.svc
    namespace: test-prod
